name: github-issue-mover
description: Issue Mover for Github
dependencies:
  forcemvc: '>=0.5.7 <0.6.0'
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  yaml: '>=0.9.0 <0.10.0'
  browser: any
  cookie: ">=0.0.4 <0.1.0"
  intl: any
  markdown: ">=0.7.0 <0.8.0"
  github:
    git:
      url: https://github.com/nicolasgarnier/github.dart
      ref: 12df15c922ea688ec1e2310c5dcdd9f0af4ff7fe
dev_dependencies:
  unittest: '>=0.10.0'
